### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod-eks-guide#1]
- [x] Use gitpod route53 domain (testing)
- [x] Allow to add auth providers after the helm chart is installed
- [x] Add external-dns and route53 to cdk stack (remove manual configuration after installation) 
- [x] Uninstall cdk stacks and remove cloud resources
- [ ] Migrate helm chart changes to gitpod.io https://github.com/aledbf/gitpod-chart-cleanup
- [x] Publish AMI in multiple regions (now only exists in us-west-2)
- [x] Make public AMI image 
- [ ] Add overview of the solution, like [this one](https://aws.amazon.com/es/blogs/architecture/field-notes-running-a-stateful-java-service-on-amazon-eks/)
- [x] Add license
- [x] Make repository public
- [x] Name of the registry bucket should be configurable or use one with the account id

**Comment by aledbf** [comment]
@tnijboer we are in the process to migrate the helm chart to a Go installer https://github.com/gitpod-io/gitpod/tree/main/installer

The GKE guide is in the process to be updated https://github.com/gitpod-io/gitpod-gke-guide/pull/12
Once that is finished, this guide and also the AKS guide will be updated.

**Comment by tnijboer** [comment]
Thanks for the update. Sounds promising. If I can test anything for the EKS deployment. Please let me know
